### ISSUE TITLE
读取不到配置文件

### ISSUE THREAD

**Issue by wangweiwei09** [yuyu1987/pithy-test#2]
![image](https://user-images.githubusercontent.com/39288409/40034798-254d964c-5831-11e8-8763-03b4dc284aa4.png)

**Comment by iris077** [comment]
遇到同样的问题，同问

**Comment by yuyu1987** [comment]
@wangweiwei09 @iris077 我在我本地调试了一下，没有遇到这个问题，还请提供一下更具体的信息

**Comment by iris077** [comment]
@yuyu1987 
![image](https://user-images.githubusercontent.com/39295889/40302296-421e5280-5d21-11e8-9a67-ea3fa3aa3f02.png)
因为cfg.py这个文件中，  os.path.exsit("cfg.yaml")  返回的是False
单独测试了下os.path.exsit(path)，只有path是当前工作目录时才返回True，其余路径都是False

**Comment by iris077** [comment]
又看了下，应该不是上面的问题。
项目的根目录，使用sys.path[0]是不是不对，在同一文件run这个取到的路径一开始是根目录，后来又变成当前工作目录。
另外还有一个问题，右击run的时候前面没有py.test，setting那边已经设置过了

**Comment by wangweiwei09** [comment]
配置文件问题已解决

**Comment by wangweiwei09** [comment]
对于读取配置文件这块有个疑问，还想请教下；源代码：
# 读取配置文件，获取当前环境配置
config = config_manager()
conf = config[config['env']]
开始在api中读取配置文件是这样写的：
    def __init__(self):
        self.base_url=conf.base_url_aaa
这样运行开始是没问题的，后来再次运行的时候就报这样的错误
AttributeError: 'dict' object has no attribute 'base_url_aaa
其他人这样写运行也是没问题的，只有我的会报这个错误；
后来我在api修改为这样的
self.base_url = conf["base_url_aaa"]   就不再报错了       
  这里不是很清楚第一种写法为什么开始没问题后来会报错

配置文件:
env: qa
qa:
    base_url_aaa: 地址：端口号
@yuyu1987

**Comment by yuyu1987** [comment]
@wangweiwei09 
这个问题是因为之前，在返回配置对象时，使用 ``JSONProcessor`` 处理了一下，支持通过点号取值。
但在去年因为一个BUG给去掉了，暂时先通过字典的方式取值好了，后面我会再优化一下。
 [https://github.com/yuyu1987/pithy-test/commit/fcb7c8bda7350e8ec89d0cc6b6efa839da55dc11#diff-5aeae35d56fe8877d344c5325607b5a7](url)

**Comment by yuyu1987** [comment]
@iris077 cfg这个模块在某些场景下（如测试项目不在根目录下等）是有问题的，之前的实现方式也不是最佳的，这个模块后面我会重新写的，谢谢提BUG ^_^

**Comment by yuyu1987** [comment]
@wangweiwei09 @iris077 这个项目是之前在公司用的，去年太忙没怎么更新过，后面我会重构一下，再适当加一些新功能，欢迎提建议，谢谢
