### ISSUE TITLE
直接调用api函数 也有触发请求，在代码里没看到

### ISSUE THREAD

**Issue by yili1992** [yuyu1987/pithy-test#3]
直接调用api函数 也有触发请求，在代码里没看到  ，请问下 到底是哪里触发 发送请求的

**Comment by yuyu1987** [comment]
@yili1992 可以看一下 api.py这个模块，调用的实现在这里面

**Comment by yili1992** [comment]
@yuyu1987 我是在api.py里面没有看到 相应的 所以来请求下 大佬  我看 发送request 是在_request() 这个函数里出发，但是_request()只有被 __getattr__ 和装饰器@context中  被调用到，我直接 调用api 函数, 没做.json和.content, 也没有.XX去获得 response 的属性，但是我看 还是出发了接口请求，觉得很奇怪，不知道还有哪里隐藏的调用

**Comment by yuyu1987** [comment]
@yili1992 可以上一下具体的代码吗，看起来并不会发送请求的

**Comment by yili1992** [comment]
@yuyu1987 奇怪了 之前一直都有触发了请求，目前确实复现不了

**Comment by yuyu1987** [comment]
@yili1992 再有问题帖代码给我看一下好了 ^_^
